[mgr]
show_hidden = true

[opener]
play = [
    { run = 'mpv "$1" --force-window', desc = "Play with mpv", for = "linux" },
    { run = 'xdg-open "$1"', desc = "Open with default", for = "linux" }
]

open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" }
]
