
animations {
    enabled = yes 

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    # bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    # animation = windows, 1, 4, myBezier
    # animation = windowsOut, 1, 3, default, popin 80%
    # animation = border, 1, 10, default
    # animation = fade, 1, 7, default
    # animation = workspaces, 1, 2, default

    # interesting animations
    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92 
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = fluent_decel, 0.1, 1, 0, 1
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    # Animation configs
    animation = windows, 1, 2, md3_decel, popin 60%
    animation = windowsIn, 1, 3, md3_decel, popin 60%
    animation = windowsOut, 1, 3, md3_accel, popin 60%
    animation = border, 1, 10, default
    animation = fade, 1, 2.5, md3_decel
    # animation = workspaces, 1, 3.5, md3_decel, slide
    # animation = workspaces, 1, 3, menu_decel, slide
    animation = workspaces, 0, 6, fluent_decel, slidefade 15%
    # animation = specialWorkspace, 1, 3, md3_decel, slidefadevert 15%
    animation = specialWorkspace, 1, 3, md3_decel, slidevert

    # bezier = overshot, 0.05, 0.9, 0.1, 1.05
    # bezier = smoothOut, 0.36, 0, 0.66, -0.56
    # bezier = smoothIn, 0.25, 1, 0.5, 1

    # animation = windows, 1, 5, overshot, slide
    # animation = windowsOut, 1, 4, smoothOut, slide
    # animation = windowsMove, 1, 4, default
    # animation = border, 1, 10, default
    # animation = fade, 1, 10, smoothIn
    # animation = fadeDim, 1, 10, smoothIn
    # animation = workspaces, 1, 6, default
}
