# exec-once = ghostty # starts up ghostty for faster terminal launch
exec-once = hyprpm reload -n
exec-once = exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK # this sometimes fixes slow startup of GTK apps
# exec-once = waybar &
exec-once = qs -c noctalia-shell
# exec-once = swww-daemon 
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = mpd
exec-once = mpris-proxy
exec-once = musicpresence # discord rich presence for music
# exec-once = swaync &
exec-once = wluma &
exec-once = flatpak run com.github.wwmm.easyeffects --gapplication-service &
# exec-once = hyprsunset &
exec-once = hypridle &
exec-once = /home/tom/.local/bin/audstopper &
exec-once = xwaylandvideobridge &
# exec-once = xwayland-satellite :0 &
exec-once = /usr/lib/kdeconnectd &
# exec-once = element-desktop --hidden &
# exec-once = /usr/bin/chromium --profile-directory=Default --app-id=ejhkdoiecgkmdpomoahkdihbcldkgjci &
exec-once = systemctl --user start polkit-gnome-authentication-agent-1.service &
exec-once = systemctl --user start graphical-session.target &
# exec-once = wl-paste -t text -w xclip -selection clipboard # fix clipboard in proton games
# exec-once = xwayland-satellite
