
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2
    gaps_out = 3
    border_size = 1
    col.active_border = $blue
    col.inactive_border = $surface1
    # no_border_on_floating = false

    layout = scrolling 

    # allow_tearing = true
}

