# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule = float, file_progress
# windowrule = float, confirm
# windowrule = float, dialog
# windowrule = float, download
# windowrule = float, notification
# windowrule = float, error
# windowrule = float, splash
# windowrule = float, confirmreset

# Steam fixes
# windowrulev2 = float, title:^()$,class:^(steam)$
# windowrulev2 = stayfocused, title:^()$,class:^(steam)$
# windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

windowrule {
    name = zoom
    match:class = ^(zoom)$
    match:title = ^()$

    stay_focused = on
    min_size = 1,1
}

windowrule {
    name = aseprite
    match:class = ^(Aseprite)$

    float = on
    stay_focused = on
    min_size = 1,1
}

windowrule {
    name = krita 
    match:title = ^(Krita)$
    match:float = true

    stay_focused = on
}

windowrule {
    name = reaper
    match:class = REAPER
    match:title = ^$

    no_blur = on
    no_focus = on
}

windowrule {
    name = windscribe
    match:class = ^(Windscribe)$
    match:title = ^(Windscribe)$

    float = on
}



# Resolve pop-ups (e.g. "Change Clip Duration")
windowrule {
    name = drpopup
    match:class = ^(resolve)$
    match:float = 1
    # tag = +drpopup
    float = on
    # stay_focused = on
    border_size = 0
    # no_border = on
    no_shadow = on
    rounding = 0
    opaque = on
}

layerrule {
    name = waybar
    match:namespace = waybar

    blur = on
}

# windowrulev2 = move cursor,class:REAPER,floating:1
# windowrulev2 = nofocus,class:REAPER,title:^(menu)$
# windowrulev2 = nofocus,class:REAPER,title:^$

# windowrulev2 = noblur, xwayland:1
windowrule = match:xwayland 1, no_blur on
#
# # Windscribe
# windowrulev2 = float,class:^(Windscribe)$,title:^(Windscribe)$
#
# # Flameshot
# windowrule = move 0 0,class:(flameshot)
# windowrule = pin,class:(flameshot)
# windowrule = noborder,class:(flameshot)
# windowrule = stayfocused,class:(flameshot)
# windowrule = float,class:(flameshot)
#
# # avoid transparency
# windowrule = opaque,class:(flameshot)
#
# # manually specify top-left-most monitor, if it's not the 0x0 monitor
# windowrule = monitor DP-2,class:(flameshot)
# # exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# windowrulev2 = opacity 0.90 override 0.90 override, title:^(Spotify)$
#
# # Davinci Resolve pop-ups (e.g. "Change Clip Duration")
# windowrulev2 = tag +drpopup, class:^(resolve)$, floating:1
#
# # Prevent Resolve from closing the popup on mouse movement / pointer leave
# windowrulev2 = stayfocused, tag:drpopup
#
# # Remove XWayland transparent margins (fixes annoying blurry borders)
# windowrulev2 = bordersize 0, tag:drpopup
# windowrulev2 = noborder,    tag:drpopup
# windowrulev2 = noshadow,    tag:drpopup
# windowrulev2 = rounding 0,  tag:drpopup
# windowrulev2 = opaque,      tag:drpopup

# Ignore maximize requests from apps. You'll probably like this.
# windowrulev2 = suppressevent maximize, class:.*
